//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/*
// Generated from: building.proto
namespace building
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cr")]
  public partial class cr : global::ProtoBuf.IExtensible
  {
    public cr() {}
    
    private uint _eventindex = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eventindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint eventindex
    {
      get { return _eventindex; }
      set { _eventindex = value; }
    }
    private ulong _building_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"building_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong building_id
    {
      get { return _building_id; }
      set { _building_id = value; }
    }
    private string _tid_level = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tid_level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tid_level
    {
      get { return _tid_level; }
      set { _tid_level = value; }
    }
    private uint _start_time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"start_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint start_time
    {
      get { return _start_time; }
      set { _start_time = value; }
    }
    private uint _end_time = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }
    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }
    private uint _wood = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"wood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint wood
    {
      get { return _wood; }
      set { _wood = value; }
    }
    private uint _stone = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"stone", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stone
    {
      get { return _stone; }
      set { _stone = value; }
    }
    private uint _iron = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"iron", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint iron
    {
      get { return _iron; }
      set { _iron = value; }
    }
    private uint _gems = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"gems", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gems
    {
      get { return _gems; }
      set { _gems = value; }
    }
    private uint _artifact_boost = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"artifact_boost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint artifact_boost
    {
      get { return _artifact_boost; }
      set { _artifact_boost = value; }
    }
    private uint _artifact_type = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"artifact_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint artifact_type
    {
      get { return _artifact_type; }
      set { _artifact_type = value; }
    }
    private uint _current_time = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"current_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint current_time
    {
      get { return _current_time; }
      set { _current_time = value; }
    }
    private uint _sync_error = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"sync_error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sync_error
    {
      get { return _sync_error; }
      set { _sync_error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"upgrade")]
  public partial class upgrade : global::ProtoBuf.IExtensible
  {
    public upgrade() {}
    
    private uint _eventindex = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eventindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint eventindex
    {
      get { return _eventindex; }
      set { _eventindex = value; }
    }
    private ulong _building_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"building_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong building_id
    {
      get { return _building_id; }
      set { _building_id = value; }
    }
    private string _status_tid_level = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status_tid_level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string status_tid_level
    {
      get { return _status_tid_level; }
      set { _status_tid_level = value; }
    }
    private uint _gold = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private uint _wood = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"wood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint wood
    {
      get { return _wood; }
      set { _wood = value; }
    }
    private uint _stone = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"stone", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stone
    {
      get { return _stone; }
      set { _stone = value; }
    }
    private uint _iron = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"iron", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint iron
    {
      get { return _iron; }
      set { _iron = value; }
    }
    private uint _gems = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"gems", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gems
    {
      get { return _gems; }
      set { _gems = value; }
    }
    private uint _start_time = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"start_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint start_time
    {
      get { return _start_time; }
      set { _start_time = value; }
    }
    private uint _end_time = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private uint _current_time = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"current_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint current_time
    {
      get { return _current_time; }
      set { _current_time = value; }
    }
    private uint _sync_error = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"sync_error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sync_error
    {
      get { return _sync_error; }
      set { _sync_error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"move")]
  public partial class move : global::ProtoBuf.IExtensible
  {
    public move() {}
    
    private ulong _building_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong building_id
    {
      get { return _building_id; }
      set { _building_id = value; }
    }
    private uint _eventindex = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"eventindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint eventindex
    {
      get { return _eventindex; }
      set { _eventindex = value; }
    }
    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }
    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }
    private uint _regions_id = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"regions_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint regions_id
    {
      get { return _regions_id; }
      set { _regions_id = value; }
    }
    private uint _current_time = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"current_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint current_time
    {
      get { return _current_time; }
      set { _current_time = value; }
    }
    private uint _sync_error = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sync_error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sync_error
    {
      get { return _sync_error; }
      set { _sync_error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"achievements")]
  public partial class achievements : global::ProtoBuf.IExtensible
  {
    public achievements() {}
    
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _tid = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tid
    {
      get { return _tid; }
      set { _tid = value; }
    }
    private string _info_tid = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"info_tid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string info_tid
    {
      get { return _info_tid; }
      set { _info_tid = value; }
    }
    private uint _action_count = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"action_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint action_count
    {
      get { return _action_count; }
      set { _action_count = value; }
    }
    private uint _diamond_reward = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"diamond_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint diamond_reward
    {
      get { return _diamond_reward; }
      set { _diamond_reward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"finish_nur")]
  public partial class finish_nur : global::ProtoBuf.IExtensible
  {
    public finish_nur() {}
    
    private ulong _building_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong building_id
    {
      get { return _building_id; }
      set { _building_id = value; }
    }
    private uint _eventindex = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"eventindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint eventindex
    {
      get { return _eventindex; }
      set { _eventindex = value; }
    }
    private uint _current_time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"current_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint current_time
    {
      get { return _current_time; }
      set { _current_time = value; }
    }
    private uint _gems = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gems", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gems
    {
      get { return _gems; }
      set { _gems = value; }
    }
    private uint _is_instant = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"is_instant", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint is_instant
    {
      get { return _is_instant; }
      set { _is_instant = value; }
    }
    private string _status_tid_level = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"status_tid_level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string status_tid_level
    {
      get { return _status_tid_level; }
      set { _status_tid_level = value; }
    }
    private uint _artifact_boost = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"artifact_boost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint artifact_boost
    {
      get { return _artifact_boost; }
      set { _artifact_boost = value; }
    }
    private uint _artifact_type = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"artifact_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint artifact_type
    {
      get { return _artifact_type; }
      set { _artifact_type = value; }
    }
    private uint _sync_error = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sync_error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sync_error
    {
      get { return _sync_error; }
      set { _sync_error = value; }
    }
    private readonly global::System.Collections.Generic.List<building.achievements> _achievement = new global::System.Collections.Generic.List<building.achievements>();
    [global::ProtoBuf.ProtoMember(10, Name=@"achievement", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<building.achievements> achievement
    {
      get { return _achievement; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cancel_nur")]
  public partial class cancel_nur : global::ProtoBuf.IExtensible
  {
    public cancel_nur() {}
    
    private ulong _building_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong building_id
    {
      get { return _building_id; }
      set { _building_id = value; }
    }
    private uint _wood = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"wood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint wood
    {
      get { return _wood; }
      set { _wood = value; }
    }
    private uint _stone = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stone", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint stone
    {
      get { return _stone; }
      set { _stone = value; }
    }
    private uint _iron = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"iron", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint iron
    {
      get { return _iron; }
      set { _iron = value; }
    }
    private uint _gold = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private uint _current_time = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"current_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint current_time
    {
      get { return _current_time; }
      set { _current_time = value; }
    }
    private uint _sync_error = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sync_error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sync_error
    {
      get { return _sync_error; }
      set { _sync_error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"removal")]
  public partial class removal : global::ProtoBuf.IExtensible
  {
    public removal() {}
    
    private uint _eventindex = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eventindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint eventindex
    {
      get { return _eventindex; }
      set { _eventindex = value; }
    }
    private ulong _building_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"building_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong building_id
    {
      get { return _building_id; }
      set { _building_id = value; }
    }
    private uint _current_time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"current_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint current_time
    {
      get { return _current_time; }
      set { _current_time = value; }
    }
    private uint _regions_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"regions_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint regions_id
    {
      get { return _regions_id; }
      set { _regions_id = value; }
    }
    private uint _removal_gold = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"removal_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint removal_gold
    {
      get { return _removal_gold; }
      set { _removal_gold = value; }
    }
    private uint _removal_gems = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"removal_gems", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint removal_gems
    {
      get { return _removal_gems; }
      set { _removal_gems = value; }
    }
    private uint _sync_error = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sync_error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sync_error
    {
      get { return _sync_error; }
      set { _sync_error = value; }
    }
    private readonly global::System.Collections.Generic.List<building.achievements> _achievement = new global::System.Collections.Generic.List<building.achievements>();
    [global::ProtoBuf.ProtoMember(8, Name=@"achievement", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<building.achievements> achievement
    {
      get { return _achievement; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqBuilding")]
  public partial class ReqBuilding : global::ProtoBuf.IExtensible
  {
    public ReqBuilding() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildingData")]
  public partial class BuildingData : global::ProtoBuf.IExtensible
  {
    public BuildingData() {}
    
    private string _tid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tid
    {
      get { return _tid; }
      set { _tid = value; }
    }
    private string _tid_type = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tid_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tid_type
    {
      get { return _tid_type; }
      set { _tid_type = value; }
    }
    private string _tid_level = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tid_level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tid_level
    {
      get { return _tid_level; }
      set { _tid_level = value; }
    }
    private string _status_tid_level = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"status_tid_level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string status_tid_level
    {
      get { return _status_tid_level; }
      set { _status_tid_level = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _regions_id = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"regions_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint regions_id
    {
      get { return _regions_id; }
      set { _regions_id = value; }
    }
    private uint _artifact_boost = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"artifact_boost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint artifact_boost
    {
      get { return _artifact_boost; }
      set { _artifact_boost = value; }
    }
    private uint _artifact_type = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"artifact_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint artifact_type
    {
      get { return _artifact_type; }
      set { _artifact_type = value; }
    }
    private uint _w_h = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"w_h", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint w_h
    {
      get { return _w_h; }
      set { _w_h = value; }
    }
    private uint _cur_hit_points = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"cur_hit_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cur_hit_points
    {
      get { return _cur_hit_points; }
      set { _cur_hit_points = value; }
    }
    private uint _cur_hit_points2 = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"cur_hit_points2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cur_hit_points2
    {
      get { return _cur_hit_points2; }
      set { _cur_hit_points2 = value; }
    }
    private uint _hit_points = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"hit_points", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hit_points
    {
      get { return _hit_points; }
      set { _hit_points = value; }
    }
    private uint _start_time = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"start_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint start_time
    {
      get { return _start_time; }
      set { _start_time = value; }
    }
    private uint _end_time = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private uint _last_collect_time = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"last_collect_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint last_collect_time
    {
      get { return _last_collect_time; }
      set { _last_collect_time = value; }
    }
    private uint _push_id = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"push_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint push_id
    {
      get { return _push_id; }
      set { _push_id = value; }
    }
    private building.BuildingData.BuildStatus _status = building.BuildingData.BuildStatus.NULL_STATUS;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(building.BuildingData.BuildStatus.NULL_STATUS)]
    public building.BuildingData.BuildStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private bool _is_destroy = default(bool);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"is_destroy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_destroy
    {
      get { return _is_destroy; }
      set { _is_destroy = value; }
    }
    private uint _troops_start_time = default(uint);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"troops_start_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint troops_start_time
    {
      get { return _troops_start_time; }
      set { _troops_start_time = value; }
    }
    private uint _troops_num = default(uint);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"troops_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint troops_num
    {
      get { return _troops_num; }
      set { _troops_num = value; }
    }
    private string _troops_tid = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"troops_tid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string troops_tid
    {
      get { return _troops_tid; }
      set { _troops_tid = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"BuildStatus")]
    public enum BuildStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NULL_STATUS", Value=0)]
      NULL_STATUS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE", Value=1)]
      CREATE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NORMAL", Value=2)]
      NORMAL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NEW", Value=3)]
      NEW = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPGRADE", Value=4)]
      UPGRADE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REMOVAL", Value=5)]
      REMOVAL = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESEARCH", Value=6)]
      RESEARCH = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRAIN", Value=7)]
      TRAIN = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CREATE_STATUE", Value=8)]
      CREATE_STATUE = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResBuilding")]
  public partial class ResBuilding : global::ProtoBuf.IExtensible
  {
    public ResBuilding() {}
    
    private readonly global::System.Collections.Generic.List<building.BuildingData> _building_data = new global::System.Collections.Generic.List<building.BuildingData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"building_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<building.BuildingData> building_data
    {
      get { return _building_data; }
    }
  
    private uint _town_hall_level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"town_hall_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint town_hall_level
    {
      get { return _town_hall_level; }
      set { _town_hall_level = value; }
    }
    private uint _laboratory_level = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"laboratory_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint laboratory_level
    {
      get { return _laboratory_level; }
      set { _laboratory_level = value; }
    }
    private uint _gunship_level = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gunship_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gunship_level
    {
      get { return _gunship_level; }
      set { _gunship_level = value; }
    }
    private uint _vault_level = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"vault_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vault_level
    {
      get { return _vault_level; }
      set { _vault_level = value; }
    }
    private uint _common_piece = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"common_piece", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint common_piece
    {
      get { return _common_piece; }
      set { _common_piece = value; }
    }
    private uint _rare_piece = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"rare_piece", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rare_piece
    {
      get { return _rare_piece; }
      set { _rare_piece = value; }
    }
    private uint _epic_piece = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"epic_piece", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint epic_piece
    {
      get { return _epic_piece; }
      set { _epic_piece = value; }
    }
    private uint _common_piece_ice = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"common_piece_ice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint common_piece_ice
    {
      get { return _common_piece_ice; }
      set { _common_piece_ice = value; }
    }
    private uint _rare_piece_ice = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"rare_piece_ice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rare_piece_ice
    {
      get { return _rare_piece_ice; }
      set { _rare_piece_ice = value; }
    }
    private uint _epic_piece_ice = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"epic_piece_ice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint epic_piece_ice
    {
      get { return _epic_piece_ice; }
      set { _epic_piece_ice = value; }
    }
    private uint _common_piece_fire = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"common_piece_fire", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint common_piece_fire
    {
      get { return _common_piece_fire; }
      set { _common_piece_fire = value; }
    }
    private uint _rare_piece_fire = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"rare_piece_fire", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rare_piece_fire
    {
      get { return _rare_piece_fire; }
      set { _rare_piece_fire = value; }
    }
    private uint _epic_piece_fire = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"epic_piece_fire", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint epic_piece_fire
    {
      get { return _epic_piece_fire; }
      set { _epic_piece_fire = value; }
    }
    private uint _common_piece_dark = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"common_piece_dark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint common_piece_dark
    {
      get { return _common_piece_dark; }
      set { _common_piece_dark = value; }
    }
    private uint _rare_piece_dark = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"rare_piece_dark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rare_piece_dark
    {
      get { return _rare_piece_dark; }
      set { _rare_piece_dark = value; }
    }
    private uint _epic_piece_dark = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"epic_piece_dark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint epic_piece_dark
    {
      get { return _epic_piece_dark; }
      set { _epic_piece_dark = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"start_train")]
  public partial class start_train : global::ProtoBuf.IExtensible
  {
    public start_train() {}
    
    private ulong _building_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong building_id
    {
      get { return _building_id; }
      set { _building_id = value; }
    }
    private uint _eventindex = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"eventindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint eventindex
    {
      get { return _eventindex; }
      set { _eventindex = value; }
    }
    private string _status_tid_level = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status_tid_level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string status_tid_level
    {
      get { return _status_tid_level; }
      set { _status_tid_level = value; }
    }
    private uint _gold = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private uint _gems = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gems", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gems
    {
      get { return _gems; }
      set { _gems = value; }
    }
    private uint _start_time = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"start_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint start_time
    {
      get { return _start_time; }
      set { _start_time = value; }
    }
    private uint _end_time = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private uint _sync_error = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sync_error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sync_error
    {
      get { return _sync_error; }
      set { _sync_error = value; }
    }
    private uint _current_time = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"current_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint current_time
    {
      get { return _current_time; }
      set { _current_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"train_finish_one")]
  public partial class train_finish_one : global::ProtoBuf.IExtensible
  {
    public train_finish_one() {}
    
    private ulong _building_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"building_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong building_id
    {
      get { return _building_id; }
      set { _building_id = value; }
    }
    private uint _eventindex = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"eventindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint eventindex
    {
      get { return _eventindex; }
      set { _eventindex = value; }
    }
    private uint _current_time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"current_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint current_time
    {
      get { return _current_time; }
      set { _current_time = value; }
    }
    private uint _troops_num = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"troops_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint troops_num
    {
      get { return _troops_num; }
      set { _troops_num = value; }
    }
    private uint _sync_error = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sync_error", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sync_error
    {
      get { return _sync_error; }
      set { _sync_error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
*/