using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MBuildingCSVStructure : BaseCSVStructure {

//	id,
//	name,
//	defense_value,
//	building_class,build_time_d,build_time_h,build_time_m,build_time_s,build_cost,town_hall_level,max_stored_resource,bunker,housing_space,produces_resource,resource_per_hour,resource_max,unit_production,upgrades_units,hit_points,regen_time,attack_range,attack_speed,damage,air_targets,ground_targets,min_attack_range,damage_radius,damage_spread,push_back,can_not_sell_last,destruction_xp,locked,hidden,trigger_radius,forges_spells,creates_artifacts,artifact_type,artifact_capacity,deepsea_resource_reward,deepsea_common_artifact_chance,deepsea_rare_artifact_chance,deepsea_epic_artifact_chance,deepsea_random_factor,deepsea_price,is_map_room,starting_energy,max_energy,energy_gain,is_vault,is_hero_house,landing_boats,can_not_move,is_global_building,explorable_regions,reload_time,shots_before_reload,resource_protection_percent,damage_over_five_seconds,counters_armored,xp_gain,tid,info_tid,subtitle_tid,swf,export_name,export_name_npc,export_name_construction,model_name,texture_name,mesh_name,width,height,icon,export_name_build_anim,destroy_effect,attack_effect,attack_effect2,attack_effect3,hit_effect,projectile,export_name_damaged,building_w,building_h,export_name_base,export_name_base_npc,pickup_effect,placing_effect,defender_character,defender_count,defender_z,export_name_tiggered,appear_effect,miss_effect,villager_probability,building_ready_effect,export_name_boss,proj_skewing,proj_y_scaling
//

}
